### ISSUE TITLE
Why does Set need Let?

### ISSUE THREAD

**Issue by trans** [cognate-lang/cognate#22]
I'm curious as to why `Set` can't just implicitly handle `Let` if need be?

So instead of,

```
Let X be Box 0;
```

We could just write,

```
Set X to 0;
```

With no need for an initial `Let`.

**Comment by StavromulaBeta** [comment]
This is because `Box` creates a generalised mutable object (a pointer) which doesn't just have to be bound to a variable - for example one could have a list of boxes. This allows the programmer to specify exactly what is mutated.

`Set` is not a syntax element like `Let` is. It's an ordinary function - when you write `Set X to 4` the box is passed to `Set` as a parameter at runtime.

This allows stuff like this 

```
Let Arr be Map (Box) over Range 1 to 10:

For each in Arr (
   Let X;
   Set X to + 1 X;
);
```
This increases each array value by 1.

If `Set` had the behaviour that you specified then this wouldn't modify the array, instead just incrementing the local variable `X` 10 times.
